### PR TITLE
fix: errors painfully added...

### PR DESCRIPTION
**Pull request by urgobalt**

### CODE REVIEW

**Comment by Alvinn8** [comment]
Which version of Rust are you using? For some reason you seem to be using different settings for `cargo fmt` since these changes contain a lot of formatting changes. My `cargo fmt` would just revert most of these changes back to how it was before. Maybe @barbariand knows why his formatter is doing this?

For example a lot of the tests, see [this one](https://github.com/barbariand/Reti/pull/11/files#diff-4223f2c4588d3e252b6dbfffc9dc8092d83a8686091bde35b404cbf7b08cff50L748-R763) for example.

**Comment by barbariand** [comment]
My cargo fmt maybe was not working

**Comment by Alvinn8** [comment]
> My cargo fmt maybe was not working

What do you mean? I think your cargo fmt, and my cargo fmt are formatting in the same way. But Ludvig's cargo fmt is formatting differently in this PR.

**Comment by barbariand** [comment]
It is beacuse its using a rustfmt.toml but if your toolchain is up to date it should work or maybe it is a nighlty vs  stable build

**Comment by barbariand** [comment]
Or idk it is doing some wierd stuff

**Comment by urgobalt** [comment]
I know there is a lot of formatting stuff. I tried to keep most of them out, but after the whole 30+ files changed thing, there was way too much on my plate. Anyway, the formatting stuff, the global settings of your rust fmt is probably different to mine. I have not changed anything but vscode might have changed some things by default. I recommend setting the line length and default values to see if that is the problem.

**Comment by barbariand** [comment]
Can you do that as a commit?

**Pull request merged**
