### PR TITLE
Adding better and working panic catching

### PR DESCRIPTION
**Pull request by barbariand**

### CODE REVIEW

**Review by urgobalt — COMMENTED** [review]
Allt ser bra ut förutom en sak: Var finns testerna för prelude? är den otestad? Finns dem i en annan plats i kodbasen?

**Comment by barbariand** [comment]
> Allt ser bra ut förutom en sak: Var finns testerna för prelude? är den otestad? Finns dem i en annan plats i kodbasen?

The parse and the spawn_logging_task functions are untested. Tbh idk how to give good testing too them. Ig just copy the tests for the ast, but how do we test for craching tasks as they are suposed to be infalible

**Comment by urgobalt** [comment]
I think we more or less test if expected output is generated from the input. You don't really need to test the infallability.

**Comment by urgobalt** [comment]
Especially, testing the different edge cases when they arise... To make sure that we don't make mistakes when editing the code later.

**Pull request merged**
